export interface Product {
  id: number,
  name: string,
  category: string,
  image: string,
  description: string,
  price: number,
  price_discount: number,
  specification: string,
  height: number,
  width: number,
  depth: number,
  weight: number,
  electrical: string,
}
